# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='objective',
            field=models.CharField(default='MEOW', max_length=200),
            preserve_default=False,
        ),
    ]
